/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001e2c',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#6ff6ff',
        'secondary-fixed-dim': '#26dcdd',
        'primary-fixed-dim': '#00dce6',
        'secondary': '#45edee',
        'primary-container': '#00f2fe',
        'surface-container-high': '#232b33',
        'inverse-primary': '#00696f',
        'on-tertiary-fixed-variant': '#004c69',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-background': '#dbe3ef',
        'outline-variant': '#3a494b',
        'error-container': '#93000a',
        'on-surface': '#dbe3ef',
        'on-secondary': '#003737',
        'on-tertiary-container': '#00678c',
        'on-secondary-container': '#005455',
        'inverse-surface': '#dbe3ef',
        'background': '#0c141c',
        'surface-variant': '#2e353e',
        'on-primary-fixed-variant': '#004f53',
        'surface-container-low': '#141c25',
        'primary': '#00f2fe',
        'on-primary-fixed': '#002022',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'surface-bright': '#323a43',
        'surface-tint': '#00dce6',
        'surface-container-lowest': '#070f17',
        'on-tertiary': '#00354a',
        'surface-container': '#182029',
        'secondary-container': '#00d0d1',
        'surface-container-highest': '#2e353e',
        'on-primary': '#00373a',
        'surface-dim': '#0c141c',
        'tertiary-container': '#b2e1ff',
        'tertiary': '#38bdf8',
        'on-surface-variant': '#94a3b8',
        'inverse-on-surface': '#29313a',
        'on-secondary-fixed-variant': '#004f50',
        'surface': '#0c141c',
        'on-primary-container': '#006a70',
        'on-secondary-fixed': '#002020',
        'tertiary-fixed': '#c4e7ff',
        'secondary-fixed': '#56f9f9',
        'outline': '#475569',
        'aqua-cyan': '#00f2fe',
        'aqua-glow': '#38bdf8',
        'aqua-deep': '#0891b2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'space-md': '1rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'space-sm': '0.75rem',
        'gutter-desktop': '2rem',
        'space-xs': '0.5rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'space-2xl': '3rem',
        'container-max': '1280px',
        'space-xxs': '0.25rem',
        'section-gap': '110px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'label-bold': ['Space Grotesk', 'sans-serif'],
        'headline-xl-mobile': ['Sora', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'display-lg-mobile': ['Sora', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      animation: {
        'pulse-glow': 'pulse-glow 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 7s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out 3.5s infinite',
        'bubble-float': 'bubble-float 4s ease-in-out infinite alternate',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: 1, transform: 'scale(1)', boxShadow: '0 0 20px rgba(0, 242, 254, 0.4), 0 0 45px rgba(56, 189, 248, 0.25)' },
          '50%': { opacity: .96, transform: 'scale(1.02)', boxShadow: '0 0 35px rgba(0, 242, 254, 0.7), 0 0 70px rgba(6, 182, 212, 0.45)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-22px)' },
        },
        'bubble-float': {
          '0%': { transform: 'translateY(0) scale(1)' },
          '100%': { transform: 'translateY(-12px) scale(1.06)' },
        },
      },
    },
  },
  plugins: [],
}